#!/bin/sh
#PKG fakeidentd
#INIT 75
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${fakeidentd:-NO}" = x"NO" && exit 0
	test x"$fakeidentd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/fakeidentd ${fakeidentd_flags}
	;;
stop)
	kill $(pgrep -f /usr/sbin/fakeidentd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
