# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

PKG_NAME:=		elf2flt
PKG_VERSION:=		20150227
PKG_RELEASE:=		1
PKG_HASH:=		9369274cf244fc090ebee08ee6eee552fba1286f63be4a558dfa149dfa91fc4c
PKG_SITES:=		http://distfiles.openadk.org/
