# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

PKG_NAME:=		elf2flt
PKG_VERSION:=		a87f68ae9e879360a9624f2a02999e67cfbe5a2f
PKG_GIT:=		hash
PKG_RELEASE:=		1
PKG_SITES:=		https://github.com/uclinux-dev/elf2flt.git
