#!/bin/sh
#PKG bind-server
#INIT 60
. /etc/rc.conf

case $1 in
autostop) ;;
	autostart)
		test x"${named:-NO}" = x"NO" && exit 0
	test x"$named" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
		exec sh $0 start
		;;
	start)
		if [ -f /etc/bind/named.conf ]; then
			/usr/sbin/named -c /etc/bind/named.conf
		fi
		;;
	stop)
		kill $(pgrep -f /usr/sbin/named)
		;;
	restart)
		sh $0 stop
		sh $0 start
		;;
	*)
		echo "usage: $0 {start | stop | restart}"
		exit 1
esac
exit $?
