#!/bin/sh
#PKG pcsc-lite
#INIT 80
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${pcscd:-NO}" = x"NO" && exit 0
	test x"$pcscd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/pcscd -f &
  	;;
stop)
	kill $(pgrep -f /usr/sbin/pcscd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "usage: $0 {start | stop | restart}"
	;;
esac
exit $?
