# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

PKG_NAME:=		libelf
PKG_VERSION:=		0.8.13
PKG_RELEASE:=		1
PKG_HASH:=		591a9b4ec81c1f2042a97aa60564e0cb79d041c52faa7416acb38bc95bd2c76d
PKG_SITES:=		http://www.mr511.de/software/
DISTFILES:=		${PKG_NAME}-${PKG_VERSION}.tar.gz
