#!/bin/sh
#PKG vsftpd
#INIT 70
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${vsftpd:-NO}" = x"NO" && exit 0
	test x"$vsftpd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	[ -d /var/run/vsftpd ] || mkdir -p /var/run/vsftpd
	/usr/sbin/vsftpd
  	;;
stop)
	kill $(pgrep -f /usr/sbin/vsftpd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "usage: $0 {start | stop | restart}"
	;;
esac
exit $?
