#!/bin/sh
#PKG pppoe-server
#INIT 50
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${pppoe_server:-NO}" = x"NO" && exit 0
	test x"$pppoe_server" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/pppoe-server
	;;
stop)
	kill $(pgrep -f /usr/sbin/pppoe-server)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
