# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

KERNEL_MAKE_OPTS:=	-C "${LINUX_DIR}" V=1 \
			CROSS_COMPILE="$(TARGET_CROSS)" ARCH=$(ARCH) \
			CC="$(TARGET_CC)" HOSTCC="${CC_FOR_BUILD}" \
			HOSTCFLAGS='${CFLAGS_FOR_BUILD}' \
			CONFIG_SHELL='${SHELL}'

ifeq (${ADK_TARGET_BROADCOM_MODEL_LINKSYS_WRT54G},y)
ADK_KCPPFLAGS+=		-DBCM47XX_OVERRIDE_FLASHSIZE=0x400000 \
			-DBCM47XX_OVERRIDE_NVRAMSIZE=0x10000 \
			-DBCM47XX_OVERRIDE_CFESIZE=0x40000
endif
ifeq (${ADK_TARGET_BROADCOM_MODEL_LINKSYS_WRT54GS},y)
ADK_KCPPFLAGS+=		-DBCM47XX_OVERRIDE_FLASHSIZE=0x800000 \
			-DBCM47XX_OVERRIDE_NVRAMSIZE=0x20000 \
			-DBCM47XX_OVERRIDE_CFESIZE=0x40000
endif
ifeq (${ADK_TARGET_BROADCOM_MODEL_ASUS_WL500GP},y)
ADK_KCPPFLAGS+=		-DBCM47XX_OVERRIDE_FLASHSIZE=0x800000 \
			-DBCM47XX_OVERRIDE_NVRAMSIZE=0x20000 \
			-DBCM47XX_OVERRIDE_CFESIZE=0x40000
endif

KERNEL_MAKE_ENV+=	KCPPFLAGS='${ADK_KCPPFLAGS}' \
			PATH="${STAGING_HOST_DIR}/usr/bin:$$PATH"
