#!/bin/sh
#PKG parprouted
#INIT 75
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${parprouted:-NO}" = x"NO" && exit 0
	test x"$parprouted" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/parprouted ${parprouted_flags}
	;;
stop)
	kill $(pgrep -f /usr/sbin/parprouted)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
