#!/bin/sh
#PKG polipo
#INIT 85
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${polipo:-NO}" = x"NO" && exit 0
	test x"$polipo" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/bin/polipo
	;;
stop)
	kill -15 $(pgrep -f /usr/bin/polipo)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
