#!/bin/sh
#PKG miredo-server
#INIT 60

. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${miredo-server:-NO}" = x"NO" && exit 0
	test x"$miredo-server" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/miredo-server
	;;
stop)
	kill $(pgrep -f /usr/sbin/miredo-server)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "usage: $0 {start | stop | restart}"
	exit 1
esac
exit $?
