#!/bin/sh
#PKG bitlbee
#INIT 80
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${bitlbee:-NO}" = x"NO" && exit 0
	test x"$bitlbee" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	mkdir -p /var/lib/bitlbee
	/usr/sbin/bitlbee -D
	;;
stop)
	kill $(pgrep -f /usr/sbin/bitlbee)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
