# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

include $(TOPDIR)/rules.mk

PKG_NAME:=		libxcb
PKG_VERSION:=		1.10
PKG_RELEASE:=		1
PKG_MD5SUM:=		a484793fbfb974b09d54fa1ebf44b2e4
PKG_DESCR:=		interface to the x window system protocol
PKG_SECTION:=		x11/libs
PKG_BUILDDEP:=		libXau-host libpthread-stubs-host xcb-proto-host
PKG_BUILDDEP+=		libxcb-host
PKG_BUILDDEP+=		python2 libpthread-stubs libxslt libXau xcb-proto
PKG_SITES:=		http://xcb.freedesktop.org/dist/
PKG_OPTS:=		dev

DISTFILES:=		${PKG_NAME}-${PKG_VERSION}.tar.gz

include $(TOPDIR)/mk/host.mk
include $(TOPDIR)/mk/package.mk

$(eval $(call HOST_template,LIBXCB,libxcb,${PKG_VERSION}-${PKG_RELEASE}))
$(eval $(call PKG_template,LIBXCB,libxcb,${PKG_VERSION}-${PKG_RELEASE},${PKG_DEPENDS},${PKG_DESCR},${PKG_SECTION},${PKG_OPTS}))

include $(TOPDIR)/mk/python.mk

CONFIGURE_ENV+=		PYTHON=$(PYTHON)

libxcb-install:
	${INSTALL_DIR} ${IDIR_LIBXCB}/usr/lib
	${CP} ${WRKINST}/usr/lib/libxcb*.so* ${IDIR_LIBXCB}/usr/lib

include ${TOPDIR}/mk/host-bottom.mk
include ${TOPDIR}/mk/pkg-bottom.mk
