#!/bin/sh
#PKG alix-switch
#INIT 10

. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${alix_switch:-NO}" = x"NO" && exit 0
	test x"$alix_switch" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/alix-switchd -d
	;;
stop)
	kill $(pgrep -f /usr/sbin/alix-switchd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "usage: $0 (start|stop|restart)"
	exit 1
esac
exit $?
