#!/bin/sh
#PKG snmpd
#INIT 60
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${snmpd:-NO}" = x"NO" && exit 0
	test x"$snmpd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	[ -d /var/lib/snmp ] || mkdir -p /var/lib/snmp
	/usr/sbin/snmpd $snmpd_flags
	;;
stop)
	kill $(pgrep -f /usr/sbin/snmpd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
