# $Id$
#-
# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

include $(TOPDIR)/rules.mk

PKG_NAME:=		xcmiscproto
PKG_VERSION:=		1.1.2
PKG_RELEASE:=		1
PKG_MD5SUM:=		3c380a728697ded97a39addfe1acf2cb
PKG_SITES:=		${MASTER_SITE_XORG}

include $(TOPDIR)/mk/package.mk

CONFIGURE_STYLE=	gnu
BUILD_STYLE=		auto
INSTALL_STYLE=		auto confprog

include ${TOPDIR}/mk/pkg-bottom.mk
