#!/bin/sh
#PKG igmpproxy
#INIT 70
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${igmpproxy:-NO}" = x"NO" && exit 0
	test x"$igmpproxy" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/igmpproxy /etc/igmpproxy.conf &
	;;
stop)
	kill $(pgrep -f /usr/sbin/igmpproxy)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	;;
esac
exit $?
