#!/bin/sh
#PKG esound
#INIT 75
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${esd:-NO}" = x"NO" && exit 0
	test x"$esd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	# start as another user via: su - mpd -c 'esd ..'
	/usr/bin/esd -public -tcp -nobeeps -noterminate &
	;;
stop)
	kill $(pgrep -f /usr/bin/esd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	;;
esac
exit 0
