#!/bin/sh
#PKG netperf
#INIT 70
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${netserver:-NO}" = x"NO" && exit 0
	test x"$netserver" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/netserver
	;;
stop)
	kill $(pgrep -f /usr/sbin/netserver)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
