#!/bin/sh
#PKG vrrpd
#INIT 70
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${vrrpd:-NO}" = x"NO" && exit 0
	test x"$vrrpd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/vrrpd $vrrpd_flags
	;;
stop)
	kill $(pgrep -f /usr/sbin/vrrpd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
 *)
	echo "usage: $0 {start | stop | restart}"
	exit 1
esac
exit $?
