#!/bin/sh
#PKG dhcp-forwarder
#INIT 80
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${dhcp_fwd:-NO}" = x"NO" && exit 0
	test x"$dhcp_fwd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/dhcp-fwd
	;;
stop)
	kill $(pgrep -f /usr/sbin/dhcp-fwd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
