# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

include $(TOPDIR)/rules.mk

PKG_NAME:=		xbitmaps
PKG_VERSION:=		1.1.0
PKG_RELEASE:=		1
PKG_MD5SUM:=		e9ab0ddd7dba49b448643768547a275d
PKG_DESCR:=		prerequiste for xsetroot
PKG_SECTION:=		x11/libs
PKG_SITES:=		http://xorg.freedesktop.org/archive/individual/app/
PKG_SUBPKGS:=

include $(TOPDIR)/mk/package.mk
include ${TOPDIR}/mk/pkg-bottom.mk
