#!/bin/sh
#PKG motion
#INIT 80
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${motion:-NO}" = x"NO" && exit 0
	test x"$motion" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	[ -f /etc/motion.conf ] || exit
	/usr/bin/motion
	;;
stop)
	kill $(pgrep -f /usr/bin/motion)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	;;
esac
exit $?
