#!/bin/sh
#PKG alsa-utils
#INIT 60
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${amixer:-NO}" = x"NO" && exit 0
	test x"$amixer" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	for shell in $(ls /etc/amixer.d/*.sh); do
		./$shell >/dev/null
	done
	;;
stop)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
