# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

PKG_NAME:=		binutils
PKG_VERSION:=		2.21
PKG_RELEASE:=		1
PKG_MD5SUM:=		c84c5acc9d266f1a7044b51c85a823f5
PKG_SITES:=		${MASTER_SITE_GNU:=binutils/}
DISTFILES:=		$(PKG_NAME)-$(PKG_VERSION).tar.bz2
