#!/bin/sh
#PKG mt-daapd
#INIT 75

. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${mt_daapd:-NO}" = x"NO" && exit 0
	test x"$mt_daapd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/mt-daapd
	;;
stop)
	kill $(pgrep -f /usr/sbin/mt-daapd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
