# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

include $(TOPDIR)/rules.mk

PKG_NAME:=		scrnsaverproto
PKG_VERSION:=		1.2.0
PKG_RELEASE:=		1
PKG_MD5SUM:=		0ed88bdd6945ba207c4f734af48e7e25
PKG_SITES:=		${MASTER_SITE_XORG}
PKG_SUBPKGS:=

include $(TOPDIR)/mk/package.mk
include ${TOPDIR}/mk/pkg-bottom.mk
