#!/bin/sh
#PKG logitechmediaserver 
#INIT 80

. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${logitechmediaserver:-NO}" = x"NO" && exit 0
	test x"$logitechmediaserver" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	chown -R squeezeboxserver /opt/lms/prefs
	perl /opt/lms/slimserver.pl
	;;
stop)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
