#!/bin/sh
#PKG mrd6
#INIT 60

. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${mrd6:-NO}" = x"NO" && exit 0
	test x"$mrd6" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/mrd6 -f /etc/mrd6.conf -D
	;;
stop)
	kill $(pgrep -f /usr/sbin/mrd6)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	;;
esac
exit $?
