#!/bin/sh
#PKG htpdate
#INIT 60

. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${htpdate:-NO}" = x"NO" && exit 0
	test x"$htpdate" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/htpdate -l -s -t $htpdate_flags && htpdate -D $htpdate_flags
	;;
stop)
	kill $(pgrep -f /usr/sbin/htpdate)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "usage: $0 {start | stop | restart}"
	exit 1
esac
exit $?
