#!/bin/sh
#PKG gmediaserver
#INIT 60
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${gmediaserver:-NO}" = x"NO" && exit 0
	test x"$gmediaserver" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/gmediaserver $gmediaserver_flags
	;;
stop)
	kill $(pgrep -f /usr/sbin/gmediaserver)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "usage: $0 (start | stop | restart)"
	exit 1
esac
exit $?
