#!/bin/sh
#PKG rarpd
#INIT 60
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${rarpd:-NO}" = x"NO" && exit 0
	test x"$rarpd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/rarpd $rarpd_flags >/dev/null 2>&1
	;;
stop)
	kill $(pgrep -f /usr/sbin/rarpd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "usage: $0 {start | stop | restart}"
	exit 1
esac
exit $?
