#!/bin/sh
#PKG srelay
#INIT 60
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${srelay:-NO}" = x"NO" && exit 0
	test x"$srelay" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	[ -f /etc/srelay.conf ] || exit 1
	/usr/bin/srelay ${srelay_flags}
	;;
stop)
	kill $(pgrep -f /usr/bin/srelay)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	;;
esac
exit $?
