#!/bin/sh
#PKG mini-httpd
#INIT 60

. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${mini_httpd:-NO}" = x"NO" && exit 0
	test x"$mini_httpd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/mini_httpd $mini_httpd_flags
	;;
stop)
	kill $(pgrep -f /usr/sbin/mini_httpd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "usage: $0 {start | stop | restart}"
	exit 1
esac
exit $?
