#!/bin/sh
#PKG bkeymaps
#INIT 6
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${kbd:-NO}" = x"NO" && exit 0
	test x"$kbd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	[ -f /usr/share/keymaps/keymap.bmap ] || exit
	loadkmap < /usr/share/keymaps/keymap.bmap
	;;
stop)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	;;
esac
exit $?
