#!/bin/sh
#PKG mpd 
#INIT 60

. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${mpd:-NO}" = x"NO" && exit 0
	exec sh $0 start
	;;
start)
	# check group membership
	id mpd | grep audio >/dev/null 2>&1
	if [ $? -ne 0 ];then
		echo "mpd user must be in group audio."
		exit 1
	fi
	mpd
	;;
stop)
	mpd --kill
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
