#!/bin/sh
#PKG xbmc 
#INIT 95

. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${xbmc:-NO}" = x"NO" && exit 0
	test x"$xbmc" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	export LD_LIBRARY_PATH=/opt/vc/lib
	xbmc &
	;;
stop)
	kill $(pgrep -f /usr/lib/xbmc/xbmc.bin)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
