#!/bin/sh
#PKG collectd
#INIT 75
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${collectd:-NO}" = x"NO" && exit 0
	test x"$collectd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	[ -d /var/lib/collectd ] || mkdir -p /var/lib/collectd
	/usr/sbin/collectd
	;;
stop)
	kill $(pgrep -f /usr/sbin/collectd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
