# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

PKG_NAME:=		uClibc
PKG_VERSION:=		0.9.30.3
PKG_RELEASE:=		1
PKG_MD5SUM:=		73a4bf4a0fa508b01a7a3143574e3d21
PKG_SITES:=		http://uclibc.org/downloads/
DISTFILES:=		$(PKG_NAME)-$(PKG_VERSION).tar.bz2
