# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

PKG_NAME:=		gmp
PKG_VERSION:=		6.1.1
PKG_RELEASE:=		1
PKG_HASH:=		d36e9c05df488ad630fff17edb50051d6432357f9ce04e34a09b3d818825e831
PKG_SITES:=		${MASTER_SITE_GNU:=gmp/}
