# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

PKG_NAME:=		gmp
PKG_VERSION:=		6.2.0
PKG_RELEASE:=		1
PKG_HASH:=		258e6cd51b3fbdfc185c716d55f82c08aff57df0c6fbd143cf6ed561267a1526
PKG_SITES:=		${MASTER_SITE_GNU:=gmp/}
