#!/bin/sh
#PKG bluez 
#INIT 90
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${bluez:-NO}" = x"NO" && exit 0
	test x"$bluez" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/libexec/bluetooth/bluetoothd &
	;;
stop)
	kill $(pgrep -f /usr/libexec/bluetooth/bluetoothd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
