# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

include $(TOPDIR)/rules.mk

PKG_NAME:=		libpthread-stubs
PKG_VERSION:=		0.1
PKG_RELEASE:=		1
PKG_MD5SUM:=		774eabaf33440d534efe108ef9130a7d
PKG_URL:=		http://xcb.freedesktop.org/
PKG_SITES:=		http://xcb.freedesktop.org/dist/
DISTFILES:=             ${PKG_NAME}-${PKG_VERSION}.tar.bz2

include $(TOPDIR)/mk/package.mk
include ${TOPDIR}/mk/pkg-bottom.mk
