# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

PKG_NAME:=		gcc
PKG_VERSION:=		4.4.1
PKG_RELEASE:=		1
PKG_MD5SUM:=		927eaac3d44b22f31f9c83df82f26436
PKG_SITES:=		${MASTER_SITE_GNU:=gcc/gcc-${PKG_VERSION}/}
DISTFILES:=		$(PKG_NAME)-$(PKG_VERSION).tar.bz2
