# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

PKG_NAME:=		gcc
PKG_VERSION:=		4.4.3
PKG_RELEASE:=		1
PKG_MD5SUM:=		fe1ca818fc6d2caeffc9051fe67ff103
PKG_SITES:=		${MASTER_SITE_GNU:=gcc/gcc-${PKG_VERSION}/}
DISTFILES:=		$(PKG_NAME)-$(PKG_VERSION).tar.bz2
