#!/bin/sh
#PKG rpcbind
#INIT 60
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${rpcbind:-NO}" = x"NO" && exit 0
	test x"$rpcbind" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/bin/rpcbind
	;;
stop)
	kill $(pgrep -f /usr/bin/rpcbind)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
