#!/bin/sh
#PKG privoxy
#INIT 70
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${privoxy:-NO}" = x"NO" && exit 0
	test x"$privoxy" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	[ -f /etc/privoxy/config ] || exit
	/usr/sbin/privoxy /etc/privoxy
	;;
stop)
	kill $(pgrep -f /usr/sbin/privoxy)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	;;
esac
exit $?
