#!/bin/sh
#PKG openvpn
#INIT 60

. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${openvpn:-NO}" = x"NO" && exit 0
	exec sh $0 start
	;;
start)
	for c in $(ls /etc/openvpn/*.conf 2>&-); do
		openvpn --cd /etc/openvpn --config "$c" --daemon
	done
	;;
stop)
	pkill openvpn
	;;
restart)
	sh $0 stop
	sleep 3
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
