#!/bin/sh
#PKG monit
#INIT 10

. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${monit:-NO}" = x"NO" && exit 0
	test x"$monit" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/monit $monit_flags
	;;
stop)
	kill $(pgrep -f /usr/sbin/monit	)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "usage: $0 (start|stop|restart)"
	exit 1
esac
exit $?
