# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

include $(TOPDIR)/rules.mk

PKG_NAME:=		renderproto
PKG_VERSION:=		0.11
PKG_RELEASE:=		1
PKG_MD5SUM:=		57216f25b9a5edc561b83a7484cb17e8
PKG_SITES:=		${MASTER_SITE_XORG}

include $(TOPDIR)/mk/package.mk
include ${TOPDIR}/mk/pkg-bottom.mk
