#!/bin/sh
if [ -z $IPKG_INSTROOT ];then chmod u+s /bin/busybox;fi
. $IPKG_INSTROOT/etc/functions.sh
add_rcconf network network YES
add_rcconf crond crond NO
add_rcconf watchdog watchdog NO
add_rcconf watchdog_flags watchdog_flags '-t 10 -T 20'
add_rcconf syslogd NO
add_rcconf 'use "-C32" normally' syslogd_flags '-C32'
add_rcconf inetd inetd NO
add_rcconf ntpd ntpd NO
add_rcconf ntpd_flags ntpd_flags '-p time.fu-berlin.de'
