#!/bin/sh
#PKG busybox
#INIT 60
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${crond:-NO}" = x"NO" && exit 0
	test x"$crond" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	mkdir -p /var/spool/cron
	/usr/sbin/crond -c /etc/crontabs
	;;
stop)
	kill $(pgrep -f /usr/sbin/crond)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
