#!/bin/sh
#PKG busybox
#INIT 41
. /etc/rc.conf
case $1 in
autostart)
	test x"${inetd:-NO}" = x"NO" && exit 0
	test -e /etc/inetd.conf || exit 0
	test x"$inetd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/inetd
	;;
autostop)
	;;
stop)
	kill $(pgrep -f /usr/sbin/inetd)
	;;
restart)
	sh $0 stop
	exec sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
