#!/bin/sh
#PKG busybox
#INIT 60
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${ntpd:-NO}" = x"NO" && exit 0
	test x"$ntpd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/ntpd $ntpd_flags >/dev/null 2>&1 &
	;;
stop)
	kill $(pgrep -f /usr/sbin/ntpd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
