#!/bin/sh
#PKG busybox
#INIT 10
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${watchdog:-NO}" = x"NO" && exit 0
	test x"$watchdog" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/sbin/watchdog $watchdog_flags /dev/watchdog
	;;
stop)
	kill $(pgrep -f /sbin/watchdog)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
