#!/bin/sh
#PKG adktest
#INIT 90
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${adktest:-NO}" = x"NO" && exit 0
	test x"$adktest" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	grep shell /proc/cmdline > /dev/null 2&>1
	if [ $? -eq 0 ];then
		exit 0
	fi
	echo "Starting test script ..."
	if [ -x /run.sh ];then
		/run.sh
		quit
	else
		echo "no run.sh found"
		quit
	fi
	;;
*)
	echo "Usage: $0 {start}"
	exit 1
	;;
esac
exit $?
