#!/bin/sh
#PKG openswan
#INIT 60
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${ipsec:-NO}" = x"NO" && exit 0
	test x"$ipsec" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/libexec/ipsec/setup start
	;;
stop)
	/usr/libexec/ipsec/setup stop
	;;
restart)
	sh $0 stop
	sleep 3
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
