#!/bin/sh
#PKG nfacctd
#INIT 80
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${nfacctd:-NO}" = x"NO" && exit 0
	test x"$nfacctd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/nfacctd $nfaccd_flags
	;;
stop)
	kill $(pgrep -f /usr/sbin/nfacctd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "usage: $0 {start | stop | restart}"
	exit 1
esac
exit $?
