#!/bin/sh
#PKG pmacctd
#INIT 80
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${pmacctd:-NO}" = x"NO" && exit 0
	test x"$pmacctd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/pmacctd $pmacctd_flags
	;;
stop)
	kill $(pgrep -f /usr/sbin/pmacctd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "usage: $0 {start | stop | restart}"
	exit 1
esac
exit $?
