# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

include $(TOPDIR)/rules.mk

PKG_NAME:=		inputproto
PKG_VERSION:=		1.4.4
PKG_RELEASE:=		1
PKG_MD5SUM:=		55c67c1f42d70458a3e4d153c8c07cf7
PKG_SITES:=		${MASTER_SITE_XORG}

include $(TOPDIR)/mk/package.mk

CONFIGURE_STYLE=	gnu
BUILD_STYLE=		auto
INSTALL_STYLE=		auto confprog

include ${TOPDIR}/mk/pkg-bottom.mk
