#!/bin/sh
#INIT 20
[[ $1 = autostart ]] || exit 0

# activate swap
[ -x /sbin/swapon ] && {
	grep swap /etc/fstab >/dev/null 2>&1
	if [ $? -eq 0 ];then
		logger -t '' "Activating swap"
		swapon -a
	fi
}

# activate any logical volumes
[ -x /usr/sbin/lvm ] && {
	logger -t '' "Activating LVM volumes"
	lvm vgscan
	lvm vgchange -ay
}

# mount local filesystems
fstypes="ext2 ext3 ext4 xfs vfat ntfs ntfs-3g"
for fs in $fstypes; do
	disks=$(grep -v "^#" /etc/fstab|grep $fs|awk '{ print $1 }')
	for disk in $disks; do
		logger -t 'Filesystem' "Found $disk with filesystem $fs"
		mnt=$(grep -v "^#" /etc/fstab|grep "${disk}[[:blank:]]"|awk '{ print $2 }')
		grep $fs /proc/filesystems >/dev/null 2>&1
		if [ $? -eq 0 ];then
			[ -x /usr/sbin/fsck.$fs ] && {
				logger -t 'Filesystem' "checking $fs filesystem on $disk"
				fsck -p $disk >/dev/null 2>&1
			}
			logger -t 'Filesystem' "Mounting $disk to $mnt"
			mkdir -p $mnt > /dev/null 2>&1
			mount $disk > /dev/null 2>&1
		else
			logger -s -t 'Filesystem' "No $fs filesystem in kernel"
		fi
	done
done
exit 0
