#!/bin/sh
#PKG xdm
#INIT 99

. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${xdm:-NO}" = x"NO" && exit 0
	test x"$xdm" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	if [ ! -d /var/lib/xdm ];then
		mkdir -p /var/lib/xdm
	fi
	xdm
	;;
stop)
	kill $(pgrep -f /usr/bin/xdm)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
