#!/bin/sh
#PKG siproxd
#INIT 60
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${siproxd:-NO}" = x"NO" && exit 0
	test x"$siproxd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/siproxd
	;;
stop)
	kill $(pgrep -f /usr/sbin/siproxd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "usage: $0 {start | stop | restart}"
	exit 1
esac
exit $?
