#!/bin/sh
#PKG jack
#INIT 78
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${jack:-NO}" = x"NO" && exit 0
	test x"$jack" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	(/usr/bin/jackd $jack_flags &) && sleep 0.1
	;;
stop)
	kill $(pgrep -f /usr/bin/jackd ) && sleep 0.1
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
