#!/bin/sh
#PKG mosquitto 
#INIT 60
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${mosquitto:-NO}" = x"NO" && exit 0
	test x"$mosquitto" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	[ -d /var/lib/mosquitto ] || mkdir -p /var/lib/mosquitto
	/usr/sbin/mosquitto $mosquitto_flags
	;;
stop)
	kill $(pgrep -f /usr/sbin/mosquitto)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
