#!/usr/bin/env bash
# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

if [ -x /usr/bin/cpio ];then
	/usr/bin/cpio --quiet "$@"
else
	/bin/cpio --quiet "$@"
fi
