#!/usr/bin/env bash
# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

if [ -x /usr/bin/md5sum ]; then
	/usr/bin/md5sum "$@"
else if [ -x /bin/md5sum ]; then
	/bin/md5sum "$@"
else
	md5 "$@" | sed 's#MD5 (\([^)]*\)) = \(.*\)#\2  \1#'
fi
fi
