#!/usr/bin/env bash
# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

if [ -z "$(which gsed 2>/dev/null)" ];then
	/bin/sed "$@"
else
	gsed "$@"
fi
