#!/bin/sh
#PKG squeezelite
#INIT 60
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${squeezelite:-NO}" = x"NO" && exit 0
	test x"$squeezelite" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/bin/squeezelite $squeezelite_flags
	;;
stop)
	kill $(pgrep -f /usr/bin/squeezelite)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "usage: $0 {start | stop | restart}"
	exit 1
esac
exit $?
