#!/bin/sh
#PKG openais
#INIT 80
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${corosync:-NO}" = x"NO" && exit 0
	exec sh $0 start
	;;
start)
	mount -t tmpfs -o size=4M tmpfs /dev/shm
	[ -d /var/lib/corosync ] || mkdir -p /var/lib/corosync
	/usr/sbin/aisexec
  	;;
stop)
	kill $(pgrep -f corosync)
	umount /dev/shm
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "usage: $0 {start | stop | restart}"
	;;
esac
exit $?
