# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

include $(TOPDIR)/rules.mk

PKG_NAME:=		damageproto
PKG_VERSION:=		1.2.0
PKG_RELEASE:=		1
PKG_MD5SUM:=		423516fd64e43e8671120056b0d9f597
PKG_SITES:=		${MASTER_SITE_XORG}
PKG_SUBPKGS:=

include $(TOPDIR)/mk/package.mk
include ${TOPDIR}/mk/pkg-bottom.mk
