#!/bin/sh
#PKG openntpd
#INIT 55
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${openntpd:-NO}" = x"NO" && exit 0
	test x"$openntpd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
        exec sh $0 start
        ;;
start)
	mkdir -p /tmp/.ntp &> /dev/null
	/usr/sbin/ntpd $openntpd_flags
	;;
stop)
	kill $(pgrep -f /usr/sbin/ntpd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
