#!/bin/sh
#PKG openct
#INIT 60
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${openct:-NO}" = x"NO" && exit 0
	test x"$openct" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	test -d /var/run/openct || mkdir -p /var/run/openct
	/usr/sbin/openct-control init
	;;
stop)
	/usr/sbin/openct-control shutdown
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "usage: $0 {start | stop | restart}"
	exit 1
esac
exit $?
