#!/bin/sh
#PKG openldap-slapd
#INIT 70
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${slapd:-NO}" = x"NO" && exit 0
	test x"$slapd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/slapd
	;;
stop)
	if [ -e /var/run/slapd.pid ]; then
		kill $(cat /var/run/slapd.pid)
	fi
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
