#!/bin/sh
#PKG ez-ipupdate
#INIT 50
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${ezipupdate:-NO}" = x"NO" && exit 0
	test x"$ezipupdate" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/ez-ipupdate -c /etc/ez-ipupdate.conf -d
	;;
stop)
	kill $(pgrep -f /usr/sbin/ez-ipupdate)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
