#!/bin/sh
#PKG tinyproxy
#INIT 70
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${tinyproxy:-NO}" = x"NO" && exit 0
	test x"$tinyproxy" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/tinyproxy
	;;
stop)
	kill $(pgrep -f /usr/sbin/tinyproxy)
	rm /var/run/tinyproxy.pid
	;;
restart)
	sh $0 stop
	sh $0 start
	;;

*)
	echo "usage: $0 {start | stop | restart}"
	exit 1
esac
exit $?
