#!/bin/sh
#PKG php-fastcgi
#INIT 80
. /etc/rc.conf

export PHP_FCGI_CHILDREN='2'

case $1 in
autostop) ;;
autostart)
	test x"${php:-NO}" = x"NO" && exit 0
	test x"$php" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/bin/php ${php_flags} &
	;;
stop)
	for i in $(pgrep -f /usr/bin/php);do kill -9 $i;done
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
