# $Id$
#-
# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

include $(TOPDIR)/rules.mk

PKG_NAME:=		xextproto
PKG_VERSION:=		7.0.3
PKG_RELEASE:=		1
PKG_MD5SUM:=		6a8f9f9559e9065858905043c17e05a1
MASTER_SITES:=		${MASTER_SITE_XORG}

include $(TOPDIR)/mk/package.mk

CONFIGURE_STYLE=	gnu
BUILD_STYLE=		auto
INSTALL_STYLE=		auto confprog

include ${TOPDIR}/mk/pkg-bottom.mk
