#!/bin/sh
#PKG scanlogd
#INIT 60
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${scanlogd:-NO}" = x"NO" && exit 0
	test x"$scanlogd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	mkdir -p `grep "^scanlogd:" /etc/passwd | cut -d: -f6`
	/usr/sbin/scanlogd $scanlogd_flags
	;;
stop)
	kill $(pgrep -f /usr/sbin/scanlogd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "usage: $0 {start | stop | restart}"
	exit 1
esac
exit $?
