#!/bin/sh
#PKG dbus
#INIT 60
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${dbus:-NO}" = x"NO" && exit 0
	test x"$dbus" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	mkdir -p /run/dbus /var/lib
	ln -sf /lib/dbus /var/lib/dbus
	/usr/bin/dbus-daemon --system
	;;
stop)
	kill $(pgrep -f /usr/bin/dbus-daemon)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
