# This file is part of the OpenADK project. OpenADK is copyrighted
# material, please see the LICENCE file in the top-level directory.

PKG_NAME:=		eglibc
PKG_VERSION:=		2.16
PKG_RELEASE:=		1
PKG_MD5SUM:=		97b0956c312e747dcead4c9459ac2aa5
PKG_SITES:=		http://openadk.org/distfiles/
