#!/bin/sh
echo "System initialization ..."
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
mount -t devtmpfs devtmpfs /dev
mount -nt proc proc /proc
mount -o nosuid,nodev,noexec -t sysfs sysfs /sys
[ ! -f /etc/notmpfs ] && {
  size=$(cat /etc/tmpfs 2>/dev/null)
  [ -z $size ] && size=2048
  mount tmpfs /tmp -t tmpfs -o nosuid,nodev,mode=1777,size=${size}k
}
mount -o remount,nosuid,size=128k,mode=0755 -t tmpfs mdev /dev
mkdir /dev/pts /dev/shm
mount -o nosuid,noexec -t devpts devpts /dev/pts
exec 0<>/dev/console >&0 2>&0
echo >/dev/mdev.seq
echo "/sbin/mdev" >/proc/sys/kernel/hotplug
mdev -s
mount -o remount,rw /
cat /etc/.rnd >/dev/urandom 2>&1
[ -f /etc/fstab ] && mount -a
[ -x /sbin/cfgfs ] && { cfgfs setup; mount -o remount,ro /;}
exec /sbin/init
