#!/bin/sh
#PKG dhcp-server
#INIT 60
. /etc/rc.conf

case $1 in
autostart)
	test x"${dhcpd:-NO}" = x"NO" && exit 0
	test x"$dhcpd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	mkdir -p /var/lib/dhcp
	touch /var/lib/dhcp/dhcpd.leases
	/usr/sbin/dhcpd $dhcpd_flags
	;;
autostop|stop)
	kill $(pgrep -f /usr/sbin/dhcpd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
