#!/bin/sh
#PKG tor
#INIT 80

. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${tor:-NO}" = x"NO" && exit 0
	exec sh $0 start
	;;
start)
	[ -d /var/run/tor ] || mkdir -p /var/run/tor
	[ -d /tmp/.tor ] || mkdir -p /tmp/.tor
	chown tor:tor /tmp/.tor /var/run/tor
	su - tor -c /usr/bin/tor
	;;
stop)
	kill $(pgrep -f /usr/bin/tor)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
