#!/bin/sh
#PKG freeradius
#INIT 75
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${radiusd:-NO}" = x"NO" && exit 0
	test x"$radiusd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	[ -d /var/log/radius ] || mkdir -p /var/log/radius
	/usr/sbin/radiusd
	;;
stop)
	kill $(pgrep -f /usr/sbin/radiusd)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
