#!/bin/sh
#PKG rrdcollect
#INIT 90
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${rrdcollect:-NO}" = x"NO" && exit 0
	test x"$rrdcollect" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	[ -d /var/lib/rrdcollect ] || mkdir -p /var/lib/rrdcollect
	/usr/sbin/rrdcollect
	;;
stop)
	kill $(pgrep -f /usr/sbin/rrdcollect)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
