#!/bin/sh
#PKG libvirt
#INIT 80
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${libvirtd:-NO}" = x"NO" && exit 0
	test x"$libvirtd" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	/usr/sbin/libvirtd -d
	;;
stop)
	kill $(pgrep -f /usr/sbin/libvirtd)
	;;
restart)
	sh $0 stop
	sleep 2
	sh $0 start
	;;
*)
	echo "usage: $0 {start | stop | restart}"
	exit 1
esac
exit $?
