#!/bin/sh
#PKG firefox
#INIT 98
. /etc/rc.conf

case $1 in
autostop) ;;
autostart)
	test x"${firefox:-NO}" = x"NO" && exit 0
	test x"$firefox" = x"DAEMON" && test -x /bin/mksh && exec mksh -T- $0 start
	exec sh $0 start
	;;
start)
	if [ ! -d /data/firefox ];then
		mkdir /data/firefox
		chown firefox /data/firefox
	fi
	su - firefox -c	startx
	;;
stop)
	;;
restart)
	sh $0 stop
	sh $0 start
	;;
*)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
	;;
esac
exit $?
